version: 0.2

phases:
  install:
    commands:
      - composer install --no-interaction --prefer-dist --optimize-autoloader
  build:
    commands:
      - php artisan key:generate
      - php artisan migrate --force
artifacts:
  files:
    - '**/*'
